field: 86b3f910-4cfc-4d23-8571-dd9ffc11c084 # Body
fieldLayouts:
  248e4059-38ac-456f-8de6-e2d8462b5154:
    tabs:
      -
        elements:
          -
            fieldUid: 1c97081f-2797-4209-8bea-c113085ba11a # Body Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a473defa-1b81-43bb-804f-da7a1e33eaca # Body Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1c97081f-2797-4209-8bea-c113085ba11a: # Body Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: bodyText
    instructions: ''
    name: 'Body Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  a473defa-1b81-43bb-804f-da7a1e33eaca: # Body Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: bodyImage
    instructions: ''
    name: 'Body Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:14317cb5-bf6f-4d3d-ad1c-84d644595b66' # Hero Images
      defaultUploadLocationSubpath: '{owner.slug}'
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:14317cb5-bf6f-4d3d-ad1c-84d644595b66' # Hero Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: bodyMain
name: 'Body Main'
sortOrder: 1
