field: 6416ecd9-732b-4444-88ba-1fe1a76bfcd8 # Gallery
fieldLayouts:
  b633e312-8e37-40a7-b124-1876eef2d1dd:
    tabs:
      -
        elements:
          -
            fieldUid: 257b372c-7c27-4549-9e6e-46c50d7b2d1b # Gallery Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86c8ca88-4c7b-4307-85e8-69f59b2ea45d # Image Desc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  86c8ca88-4c7b-4307-85e8-69f59b2ea45d: # Image Desc
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: imageDesc
    instructions: ''
    name: 'Image Desc'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: 'Descriptive Text'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  257b372c-7c27-4549-9e6e-46c50d7b2d1b: # Gallery Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: galleryImage
    instructions: ''
    name: 'Gallery Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:14317cb5-bf6f-4d3d-ad1c-84d644595b66' # Hero Images
      defaultUploadLocationSubpath: '{owner.slug}'
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:14317cb5-bf6f-4d3d-ad1c-84d644595b66' # Hero Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: galleryItem
name: 'Gallery Item'
sortOrder: 2
