field: 399170ae-121d-4a53-8194-04dfd0cd088a # Image Strip
fieldLayouts:
  9ee6306f-2b6f-4066-9c70-3194db9ac1f2:
    tabs:
      -
        elements:
          -
            fieldUid: f51a9d9d-6c4b-42df-8ad8-3204091501de # Strip Header
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0724bef4-cf1e-464a-a091-879af218fc23 # Strip Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c913b221-11f0-4caa-899a-d370b3a7e450 # Strip Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0724bef4-cf1e-464a-a091-879af218fc23: # Strip Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stripText
    instructions: ''
    name: 'Strip Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c913b221-11f0-4caa-899a-d370b3a7e450: # Strip Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: stripImage
    instructions: ''
    name: 'Strip Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:14317cb5-bf6f-4d3d-ad1c-84d644595b66' # Hero Images
      defaultUploadLocationSubpath: '{owner.slug}'
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:14317cb5-bf6f-4d3d-ad1c-84d644595b66' # Hero Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f51a9d9d-6c4b-42df-8ad8-3204091501de: # Strip Header
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stripHeader
    instructions: ''
    name: 'Strip Header'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: strip
name: Strip
sortOrder: 1
