columnSuffix: null
contentColumnType: string
fieldGroup: e9563268-af59-4acf-a453-038bd1f8211c # Carousel
handle: hero
instructions: ''
name: Hero
searchable: false
settings:
  contentTable: '{{%matrixcontent_hero}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
