columnSuffix: null
contentColumnType: string
fieldGroup: ea389470-904f-4f5c-b20f-f8b274a93528 # Navigation
handle: relatedEntry
instructions: ''
name: 'Related Entry'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
