columnSuffix: gnexzjwh
contentColumnType: 'decimal(12,2)'
fieldGroup: c26cdf24-9153-4a54-875e-6c1cef19f1b2 # Products
handle: retailPrice
instructions: ''
name: 'Retail Price'
searchable: false
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: GBP
  previewFormat: currency
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
