columnSuffix: null
contentColumnType: string
fieldGroup: e9563268-af59-4acf-a453-038bd1f8211c # Carousel
handle: socialMedia
instructions: ''
name: 'Social Media'
searchable: false
settings:
  contentTable: '{{%matrixcontent_socialmedia}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
