defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  ff5f6e13-635b-454c-83ae-39e81c2a5f3f: # The Print Works
    enabledByDefault: true
    hasUrls: true
    template: _routers/main
    uriFormat: __home__
type: single
