defaultPlacement: end
enableVersioning: true
handle: products
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ff5f6e13-635b-454c-83ae-39e81c2a5f3f: # The Print Works
    enabledByDefault: true
    hasUrls: true
    template: _routers/main
    uriFormat: products
type: single
