columnSuffix: oswnwnno
contentColumnType: text
fieldGroup: ea389470-904f-4f5c-b20f-f8b274a93528 # Navigation
handle: pageName
instructions: ''
name: 'Page Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
