columnSuffix: cdmdujuy
contentColumnType: string(255)
fieldGroup: ea389470-904f-4f5c-b20f-f8b274a93528 # Navigation
handle: relatedUrl
instructions: ''
name: 'Related Url'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
